# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 16:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('trailer', models.URLField(blank=True, null=True)),
                ('dec', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Threater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theaters', to='main.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.CharField(max_length=140)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='main.Movie')),
                ('theaters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='main.Threater')),
            ],
        ),
    ]
